import Head from 'next/head';
import { useEffect } from 'react';
// import Image from 'next/image';
import Banner from '../components/Banner';
import Card from '../components/Card';
import { useLocation } from '../hooks/useLocation';
import { shopsGet } from '../services/shops';
import styles from '../styles/Home.module.css';

export async function getStaticProps() {
	const shops = await shopsGet();

	return {
		props: { shops }
	};
};

function Home({ shops }) {
	const { locate, coordinates, loading, error } = useLocation();

	const onButtonClick = () => {
		locate();
	};
	
	return (
		<div className={styles.container}>
			<Head>
				<meta name='description' content='Generated by CNA' />
				<title>Coffee Connoisseur</title>
				<link rel='icon' type='image/x-icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.hero}>
					{/* <Image src='/hero.png' alt='hero' width={700} height={400} /> */}
				</div>
				<Banner buttonText={loading ? 'Locating...' : 'Locate Shops Near Me'} onButtonClick={onButtonClick} />
				{error && <pre>Error: {error}</pre>}
				<div className={styles.sectionWrapper}>
					{shops.length > 0 && (
						<>
							<h2 className={styles.heading2}>London Shops</h2>
							<section className={styles.cardLayout}>
								{shops.map(({ ID, name, imageURL }) => (
									<Card key={ID} name={name} imageURL={imageURL} href={`/shop/${ID}`} />
								))}
							</section>
						</>
					)}
				</div>
			</main>
		</div>
	);
};

export default Home;