import Head from 'next/head';
import styles from '../styles/Home.module.css';

function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<meta name='description' content='Generated by CNA' />
				<title>Coffee Connoiseur</title>
				<link rel='icon' type='image/x-icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<h1 className={styles.title}>Coffee Connoiseur</h1>
			</main>
		</div>
	);
};

export default Home;