import Head from 'next/head';
import Banner from '../components/Banner';
import styles from '../styles/Home.module.css';

function Home() {
	const onButtonClick = () => {
		console.log('CLICK');	
	};
	
	return (
		<div className={styles.container}>
			<Head>
				<meta name='description' content='Generated by CNA' />
				<title>Coffee Connoiseur</title>
				<link rel='icon' type='image/x-icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Banner buttonText='Locate Shops Near Me' onButtonClick={onButtonClick} />
			</main>
		</div>
	);
};

export default Home;